
import React, { useContext , useEffect} from 'react'
import Footer from "../components/Footer"
import Navbar from "../components/Navbar"
import { AuthContext } from '../context/authContextProvider';
import { useNavigate } from 'react-router-dom';



const FeatureCard = ({ title, desc }) => (
  <div className="bg-gray-900/50 border border-gray-800 rounded-2xl p-6 shadow-md backdrop-blur-sm">
    <h4 className="text-lg font-semibold text-white mb-2">{title}</h4>
    <p className="text-sm text-gray-300">{desc}</p>
  </div>
);
const Home = () => {
  const {authUser} = useContext(AuthContext)
  const navigate = useNavigate()
  useEffect(() => {
  if (authUser) {
    navigate("/profile");
  }
}, [authUser, navigate]);
  return (
    <div>
      <Navbar/>
      <div className="min-h-screen bg-gradient-to-b from-[#0b1020] via-[#08080d] to-[#050507] text-white mt-0 pt-0 mb-0">
      <main className="max-w-7xl mx-auto px-6">
        <section className="grid grid-cols-1 md:grid-cols-2 gap-8 items-center py-12 md:py-20">
          <div>
            <p className="inline-block px-3 py-1 rounded-full text-xs font-medium text-indigo-200 border-gray-900 bg-indigo-900/30">AI Powered</p>
            <h2 className="mt-3 text-4xl md:text-5xl font-extrabold leading-tight">
              Ace Interviews with
              <span className="block text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 to-cyan-600"> AI-Powered Learning</span>
            </h2>
            <p className="mt-6 text-gray-300 max-w-xl">
              Get role-specific questions, expand answers when you need them, dive deeper into concepts, and organize everything your way. Your ultimate interview toolkit is here.
            </p>


            <div className="mt-8 flex gap-4">
              <button  className="px-6 py-3 rounded-lg bg-indigo-500 hover:bg-indigo-600 font-semibold" onClick={() => navigate('/profile')} >Get Started</button>
              <button className="px-6 py-3 rounded-lg bg-transparent border border-gray-700 text-gray-300">Learn More</button>
            </div>


            <div className="mt-8 text-sm text-gray-400 grid grid-cols-2 gap-3 max-w-md">
              <div className="bg-gray-900/30 p-3 rounded-lg">Tailored just for you</div>
              <div className="bg-gray-900/30 p-3 rounded-lg">Save, organize and revisit</div>
            </div>
          </div>


          <div className="relative">
            {/* Mockup frame */}
            <div className="rounded-2xl border border-gray-800 bg-gradient-to-b from-[#0b1120]/50 to-[#0b0b12]/40 p-4 shadow-2xl">
              <div className="rounded-xl overflow-hidden bg-gradient-to-b from-white/6 to-white/3">
                {/* Top chrome */}
                <div className="flex items-center gap-2 px-4 py-3 bg-black/10">
                  <div className="w-3 h-3 rounded-full bg-red-500"></div>
                  <div className="w-3 h-3 rounded-full bg-yellow-400"></div>
                  <div className="w-3 h-3 rounded-full bg-green-400"></div>
                </div>


                {/* Image inside - responsive */}
                <div className="p-4 bg-gradient-to-b from-gray-900 to-gray-800">
                  <img src="/assets/hero-screenshot.jpg" alt="hero" className="w-full h-64 object-cover rounded-md shadow-inner" />
                </div>


                {/* footer preview */}
                <div className="p-4 bg-black/20 text-gray-300 text-sm">Frontend Developer | Interview Q&amp;A preview</div>
              </div>
            </div>


            {/* decorative badge */}
            <div className="absolute -bottom-6 left-6 bg-gradient-to-br from-cyan-400 to-cyan-600 text-black px-4 py-2 rounded-2xl font-semibold shadow-lg">Live Demo</div>
          </div>
        </section>


        {/* FEATURES */}
        <section id="features" className="py-12 md:py-20">
          <h3 className="text-center text-2xl font-bold mb-8">Features That Make You Shine</h3>


          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
            <FeatureCard title="Tailored Just for You" desc="Get interview questions and model answers based on your role, experience, and specific focus areas." />
            <FeatureCard title="Learn at Your Own Pace" desc="Expand answers only when you're ready. Dive deeper into any concept with AI-powered explanations." />
            <FeatureCard title="Capture Your Insights" desc="Add personal notes to any question and pin important ones to help organize your learning." />
            <FeatureCard title="Understand the Why" desc="Unlock detailed concept explanations generated by AI to truly master each topic." />
            <FeatureCard title="Save, Organize, and Revisit" desc="Easily save interview sets, organize them neatly, and pick up where you left off." />
            <FeatureCard title="Role-specific Practice" desc="Practice with curated sets tailored to frontend, backend, data, and more." />
          </div>
        </section>


        {/* CTA BAR */}
      </main>
      </div>
      <Footer/>
    </div>
  )
}

export default Home